metadata/objects/Competitor__c.object
<CustomObject>
    <description>This object is a central hub to track all they key information about your competitors</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/objects/Competitor_Product__c.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <label>Competitor</label>
        <referenceTo>Competitor__c</referenceTo>
        <relationshipLabel>Competitor Products</relationshipLabel>
        <relationshipName>Competitor_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cons__c</fullName>
        <label>Cons</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Features__c</fullName>
        <label>Features</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pros__c</fullName>
        <label>Pros</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Competitor Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/objects/Customer_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor Product</label>
        <referenceTo>Competitor_Product__c</referenceTo>
        <relationshipLabel>Customer Feedbacks</relationshipLabel>
        <relationshipName>Customer_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Feedback</label>
    <nameField>
        <displayFormat>CF-{00000000}</displayFormat>
        <label>Customer Feedback #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/classes/CustomerFeedbackExtension.cls
public class CustomerFeedbackExtension {
    public boolean error {get; set;}
    public string competitor {get; set;}
    public string competitorName {get; set;}
    public string product {get; set;}
    public double price {get; set;}
    public string otherProduct {get; set;}
    public string features {get; set;}
    public string pros {get; set;}
    public string cons {get; set;}
    public boolean showName {get; set;}
    public boolean showPrdName {get; set;}
    public map<Id, Competitor_Product__c> mapCP = new map<Id, Competitor_Product__c>();

    public Customer_Feedback__c cf;
    public string retURL {get; set;}

    public list<SelectOption> getCompetitorOptions() {
        list<SelectOption> options = new list<SelectOption>();
        options.add(new SelectOption('', '--None--'));

        for (Competitor__c co:[SELECT Id, Name FROM Competitor__c]) {
            options.add(new SelectOption(co.Id, co.Name));
        }

        options.add(new SelectOption('Other', 'Other'));

        return options;
    }

    public list<SelectOption> getProductOptions() {
        list<SelectOption> options = new list<SelectOption>();
        options.add(new SelectOption('', '--None--'));

        for (Competitor_Product__c cp:mapCP.values()) {
            options.add(new SelectOption(cp.Id, cp.Name));
        }

        options.add(new SelectOption('Other', 'Other'));

        return options;
    }


    public CustomerFeedbackExtension(ApexPages.StandardController controller) {
        cf = (Customer_Feedback__c) controller.getRecord();

        retURL = ApexPages.currentPage().getParameters().get('retURL');

        showName = false;
        showPrdName = false;
    }

    public PageReference showProduct() {
        if (competitor == 'Other') {
            showName = true;
            mapCP = new map<Id, Competitor_Product__c>();
            price = null;
        }
        else {
            showName = false;
            competitorName = null;

            mapCP = new map<Id, Competitor_Product__c>([SELECT Id, Name, Competitor__c, Price__c, Features__c, Pros__c, Cons__c FROM Competitor_Product__c WHERE Competitor__c = :competitor]);
            price = null;
        }

//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, competitor));
        return null;
    }

    public PageReference showProductName() {
        if (product == 'Other') {
            showPrdName = true;
            price = null;
        }
        else {
            showPrdName = false;
            otherProduct = null;
            if (mapCP.containsKey(product)) {
                price = Double.valueOf(mapCP.get(product).Price__c);
                features = mapCP.get(product).Features__c;
                pros = mapCP.get(product).Pros__c;
                cons = mapCP.get(product).Cons__c;
            }
            else {
                price = null;
                features = null;
                pros = null;
                cons = null;
            }
        }

//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, product + ' -- ' + price));
        return null;
    }

    public PageReference save() {
        error = true;
        if (competitor == null || competitor == '') {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please select Competitor'));
            return null;
        }

        if (competitor == 'Other' && (competitorName == null ||competitorName == '')) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please enter Competitor Name'));
            return null;
        }

        if (product == null || product == '') {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please select Product'));
            return null;
        }

        if (product == 'Other' && (otherProduct == null || otherProduct == '')) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please enter Product Name'));
            return null;
        }

        //create temp entry for Product and Competitor and take feedback.
        if (competitor == 'Other') {
            Competitor__c comp = new Competitor__c(Name = competitorName);
            insert comp;

            Competitor_Product__c compProd = new Competitor_Product__c(Name = otherProduct, Competitor__c = comp.Id, Price__c = price, Features__c = features, Pros__c = pros, Cons__c = cons);
            insert compProd;

            cf.Competitor_Product__c = compProd.Id;
        }
        else
            cf.Competitor_Product__c = product;

        try {
            upsert cf;
        }
        catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage()));
            return null;
        }

        error = false;

        PageReference pr = new PageReference(retURL);
        return pr;
    }

    public PageReference cancel() {
        PageReference pr = new PageReference(retURL);
        return pr;
    }
}